version: "3"
services:
  postgres:
    image: postgres:12
    #    ports:
    #      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: image-metadata
  image-catalog:
    image: baraba123/rso-image-catalog:1.0.0-SNAPSHOT-2.1
    ports:
      - 8080:8080
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://postgres:5432/image-metadata
    #      KUMULUZEE_CONFIG_ETCD_HOSTS: http://etcd:2379
    #      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
    depends_on:
      - postgres
#      - etcd
#  etcd:
#    image: quay.io/coreos/etcd:latest
#    ports:
#      - "2379:2379"
#    command: >-
#      /usr/local/bin/etcd
#      -name node1
#      -advertise-client-urls http://etcd:2379
#      -listen-client-urls http://0.0.0.0:2379
#      -initial-advertise-peer-urls http://etcd:2380
#      -listen-peer-urls http://0.0.0.0:2380
#      -initial-cluster node1=http://etcd:2380
#      -cors="*"