kumuluzee:
  name: rso-image-catalog
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ImageMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/image-metadata
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://192.168.2.195:2379
  discovery:
    etcd:
      hosts: http://192.168.2.195:2379
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ImageMetadataDS
      etcd-health-check:
        connection-url: http://192.168.2.195:2379/health
  metrics:
    web-instrumentation:
      - name: images-endpoint
        url-pattern: /v1/images/*
configuration-properties:
  recomender-service:
    enabled: true