kumuluzee:
  name: rso-image-catalog
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ImageMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/image-metadata
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://192.168.2.195:2379
  discovery:
    etcd:
      hosts: http://192.168.2.195:2379
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ImageMetadataDS
      etcd-health-check:
        connection-url: http://192.168.2.195:2379/health
  metrics:
    web-instrumentation:
      - name: images-endpoint
        url-pattern: /v1/images/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                        <Configuration name="images-catalog">
                            <Appenders>
                                <Console name="console" target="SYSTEM_OUT">
                                    <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                </Console>
                                <Socket name="logstash" host="616fab46-e681-4bed-8c25-6fbca4d256d4-ls.logit.io"
                                port="23106" protocol="tcp">
                                    <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                </Socket>
                            </Appenders>
                            <Loggers>
                                <!-- Default logger -->
                                <Root level="all">
                                    <AppenderRef ref="console" level="info"/>
                                    <AppenderRef ref="logstash" level="trace"/>
                                </Root>
                            </Loggers>
                        </Configuration>'
configuration-properties:
  recomender-service:
    enabled: true