kumuluzee:
  name: rso-image-catalog
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ImageMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/image-metadata
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://10.10.80.79:2379
  discovery:
    etcd:
      hosts: http://10.10.80.79:2379
configuration-properties:
  recomender-service:
    enabled: true