INSERT INTO image_metadata (title, description, uri) VALUES ('1000092795.jpg', ' Two young guys with shaggy hair look at their hands while hanging out in the yard .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('10002456.jpg', ' Several men in hard hats are operating a giant pulley system .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1000268201.jpg', ' A child in a pink dress is climbing up a set of stairs in an entry way .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1000344755.jpg', ' Someone in a blue shirt and hat is standing on stair and leaning against a window .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1000366164.jpg', ' Two men , one in a gray shirt , one in a black shirt , standing near a stove .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1000523639.jpg', ' Two people in the photo are playing the guitar and the other is poking at him .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1000919630.jpg', ' A man sits in a chair while holding a large stuffed animal of a lion .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('10010052.jpg', ' A girl is on rollerskates talking on her cellphone standing in a parking lot .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1001465944.jpg', ' An asian man wearing a black suit stands near a dark-haired woman and a brown-haired woman .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1001545525.jpg', ' Two men in Germany jumping over a rail at the same time without shirts .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1001573224.jpg', ' Five ballet dancers caught mid jump in a dancing studio with sunlight coming through a window .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1001633352.jpg', ' Three young men and a young woman wearing sneakers are leaping in midair at the top of a flight of concrete stairs .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1001773457.jpg', ' A black dog and a white dog with brown spots are staring at each other in the street .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1001896054.jpg', ' A man with reflective safety clothes and ear protection drives a John Deere tractor on a road .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('100197432.jpg', ' Some women are standing in front of a bus with buildings behind it .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('100207720.jpg', ' A young woman with dark hair and wearing glasses is putting white powder on a cake using a sifter .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1002674143.jpg', ' A small girl in the grass plays with fingerpaints in front of a white canvas with a rainbow on it .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1003163366.jpg', ' a man sleeping on a bench outside with a white and black dog sitting next to him .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1003420127.jpg', ' A group of adults , inside a home , sitting on chairs arranged in a circle , playing a type of musical instruments .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1003428081.jpg', ' Two women , both wearing glasses , are playing clarinets and an elderly woman is playing a stringed instrument .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('100444898.jpg', ' A person in gray stands alone on a structure outdoors in the dark .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1005216151.jpg', ' A man in a white t-shirt looks toward the camera surrounded by a crowd near a metro station .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('100577935.jpg', ' A man with a goatee in a black shirt and white latex gloves is using a tattoo gun to place a tattoo on someone s back .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1006452823.jpg', ' two children , a girl and a boy are practicing their writing .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('100652400.jpg', ' A man in a blue hard hat and orange safety vest stands in an intersection while holding a flag .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1007129816.jpg', ' The man with pierced ears is wearing glasses and an orange hat .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('100716317.jpg', ' A person with long gray hair has a beret with beige and white wearing a blue raincoat is painting a marketplace scenery surrounded by other artists and paintings .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1007205537.jpg', ' A man stands on one foot while holding on to a waste basket .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1007320043.jpg', ' A small child grips onto the red ropes at the playground .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('100759042.jpg', ' Young man in jacket holding a toothpick with something on the end of it','');
INSERT INTO image_metadata (title, description, uri) VALUES ('10082347.jpg', ' Young blond man in a blue and yellow jacket smiling while standing in front of a net .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('10082348.jpg', ' A man with a baseball cap and black jacket stands in a bathroom while holding a coffee mug .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('100845130.jpg', ' Five people walking with a multicolored sky in the background .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('10090841.jpg', ' A man with black hair sits in a restaurant with a glass of beer .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1009434119.jpg', ' A black and white dog is running in a grassy garden surrounded by a white fence .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1009692167.jpg', ' An officer in a reflective vest stands at the front of his van with his dog .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('101001624.jpg', ' The conditions of snow on the ground seem to almost obliverate the details of a man dressed for the cold weather in a heavy jacket and red hat riding a bicycle in a suburban neighborhood .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1010031975.jpg', ' Five men , uniformly dressed in white shirts , tie and black slacks converse at the back of an open van .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1010087179.jpg', ' A tan man with a backwards hat looks at the camera while walking through a factory .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1010087623.jpg', ' A caucasian man wearing a short-sleeved black shirt and a dark-skinned woman wearing a sleeveless dress are working at a conveyor .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('10101477.jpg', ' Man wearing a blue and white outfit , holding a broom , with a traditional Asian architecture in the background .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1010470346.jpg', ' two men in florescent vests are standing next to parked cars in front of a small building while one of them converses with a driver and a woman on a bike is seen riding by','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1010673430.jpg', ' A little girl in a pink shirt and a little girl in an orange shirt sitting in the grass .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('101093029.jpg', ' A person in tan pants is inside a silver mobile object while people watch .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('101093045.jpg', ' A man in black approaches a strange silver object containing a person , while many onlookers observe from behind a roped off barrier .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1011572216.jpg', ' bride and groom walking side by side out of focus on pathway next to brick building .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1012150929.jpg', ' A little boy plays with a Nintendo GameCube controller inside a McDonald s .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1012212859.jpg', ' White dog with brown ears standing near water with head turned to one side .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1012328893.jpg', ' A group of people picnicking at picnic tables in front of a playground .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('101262930.jpg', ' Two asian or spanish people , a woman and a man , sitting together in front of a glass window as cars pass .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1013536888.jpg', ' Women are seated at a picnic table eating , while a man in a white t-shirt and a yellow and orange balloon design on his head stands in the background .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('101362133.jpg', ' A young female student performing a downward kick to break a board held by her Karate instructor .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('101362650.jpg', ' Two people are demonstrating martial arts to a crowd and jumping over three youngsters who are crouched on the mat .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1014609273.jpg', ' People on two balconies and a man climbing up a pipe towards the lower balcony getting liquid poured on him .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('101471792.jpg', ' A man with a red jacket is shielding himself from the sun trying to read a piece of paper .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1014785440.jpg', ' Two men are carrying children on their backs down the street on a sunny day in a nice neighborhood .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1015118661.jpg', ' Smiling boy in white shirt and blue jeans in front of rock wall with man in overalls behind him .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1015584366.jpg', ' A mottled black and gray dog in a blue collar jumping over a fallen tree .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('101559400.jpg', ' Men in the business suits are crossing the street , and there are people with placards are gathering on the street .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1015712668.jpg', ' A man in a red long-sleeved shirt bikes over a body of water on a bridge .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('10160966.jpg', ' A barefooted man wearing olive green shorts grilling hotdogs on a small propane grill while holding a blue plastic cup .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('101654506.jpg', ' The white and brown dog is running over the surface of the snow .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1016626169.jpg', ' Man on scooter attracts attention from some of those in large crowd .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('101669240.jpg', ' A person wearing skis looking at framed pictures set up in the snow .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1016887272.jpg', ' Several climbers in a row are climbing the rock while the man in red watches and holds the line .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1017675163.jpg', ' A young gymnast , jumps high in the air , while performing on a balance beam .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1018057225.jpg', ' a boy in a black t-shirt and blue jeans is pushing a toy three wheeler around a small pool .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1018148011.jpg', ' A group of people stand in the back of a truck filled with cotton .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('101859883.jpg', ' a woman with a red jacket and headscarf looks out over a scenic view of a bay through a set of pay binoculars on a viewing deck .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('10188041.jpg', ' A man in a black coat walks past a red spaceship with a parking ticket stuck to its window .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1019077836.jpg', ' Large brown dog running away from the sprinkler in the grass .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('101958970.jpg', ' A man and a little girl happily posing in front of their cart in a supermarket .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1019604187.jpg', ' A dog prepares to catch a thrown object in a field with nearby cars .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('102030371.jpg', ' A man wearing a green shirt and a dark colored vest is sitting at a table with a glass of water in front of him .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1020651753.jpg', ' A white dog is trying to catch a ball in midair over a grassy field .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1021293940.jpg', ' Two men are hiking in a forest where snow is partially covering the ground .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1021332107.jpg', ' An elderly man with facial hair and glasses , standing in his living room holding a hutch cabinet with glass doors .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1021439420.jpg', ' two guys sitting on the floor , with the guy in the green jacket reading a piece of paper .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1021442086.jpg', ' A bearded man wearing glasses , a red shirt , and a hat is reading a map while sitting in a car .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1022454332.jpg', ' a large lake with a lone duck swimming in it with several people around the edge of it .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1022454428.jpg', ' A couple and an infant , being held by the male , sitting next to a pond with a nearby stroller .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('102268204.jpg', ' Three men are standing at night near a black car near a shelter filled with bicycles .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1022975728.jpg', ' A black lab with tags frolicks in the water .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('102351840.jpg', ' A man is drilling through the frozen ice of a pond .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1024138940.jpg', ' Two different breeds of brown and white dogs play on the beach .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('102455176.jpg', ' an ice climber in a blue jacket and black pants is scaling a frozen ice wall .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1024613706.jpg', ' Two young men and a young lady walk through a field near the water .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('102520526.jpg', ' A man in black attire shovels snow into the street , disregarding all public safety .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('102575576.jpg', ' A couple in their wedding attire stand behind a table with a wedding cake and flowers .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1026685415.jpg', ' A black dog carries a green toy in his mouth as he walks through the grass .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1026792563.jpg', ' A group of woman and children are standing or sitting in front of rows of vegetables .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1027149103.jpg', ' A band is playing in front of an audience and the singer is wearing an orange shirt and has tattoos on his arm .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1027211271.jpg', ' A young woman with short blond-hair wearing jeans and a striped long-sleeved sweater jumping in midair on a skateboard with trees in the background .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1028205764.jpg', ' A man and a little boy in blue life jackets are rowing a yellow canoe .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('102851549.jpg', ' A little boy looks at the camera while a woman behind him seems to be laughing very hard and the woman on the right has a big smile on her face .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('102860573.jpg', ' A construction site on a street with three men working .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('10287332.jpg', ' Two men sitting on the roof of a house while another one stands on a ladder .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1028982826.jpg', ' Two men , one younger guy with a yellow shirt that has luggage and the other and older guy , are sitting on a bench in front of a large building that has a billboard for glasses and sunglasses .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1029450589.jpg', ' An adult wearing a gray shirt with red sleeves sleeping on a couch .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1029737941.jpg', ' Boy in brown shirt with headphones on sits on woman s shoulders in a crowd .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1029802110.jpg', ' During a gay pride parade in an Asian city , some people hold up rainbow flags to show support .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('102998070.jpg', ' A young man in a blue sweater cleaning fish while three other men watch , one a man a cigarette , or match in his month .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1030041880.jpg', ' Woman in a green dress with a white top and red-hair singing in a room with a blue roof while band equipment is being prepared .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('103031977.jpg', ' Four college-aged individuals - two males and two females - sitting on the concrete steps outside of a brick building','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1030985833.jpg', ' The Chocolate Lab jumps too late to get the toy as the Black Lab captures it in the driveway .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('103106960.jpg', ' A young male kneeling in front of a hockey goal with a hockey stick in his right hand .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('103195344.jpg', ' The man with the backpack is sitting in a buildings courtyard in front of an art sculpture reading .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1031973097.jpg', ' A toddler in a blue shirt with red shorts and hat looks out from behind a fenced in area of a brick patio .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('103205630.jpg', ' Two men , standing on an ice , looking into something covered with a blue tarp .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1032122270.jpg', ' Three dogs are standing in the grass and a person is sitting next to them','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1032460886.jpg', ' There is a skyscraper in the distance with a man walking in front of the camera .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('103306033.jpg', ' A woman wearing a brown dress with a matching turban is pushing a toddler through a park in his stroller .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('103328091.jpg', ' A Asian male wearing a red shirt is sitting next to a grocery stand selling fruits .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1033767085.jpg', ' a young child with a Band-Aid on his head sits eating at a small white table with a little girl eating off a yellow plate .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1034276567.jpg', ' A small boy putting something in his mouth with both hands .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1034985636.jpg', ' A man with wild hair rocks a show playing a guitar center stage .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1035019794.jpg', ' A person in a green outfit and helmet is swinging a baseball bat at a tennis ball in front of a fence .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('10350842.jpg', ' A man in a green shirt and red life jacket is sitting in a canoe drifting around the lake .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1035392784.jpg', ' A man in black with long hair playing a guitar with stickers on it .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('103625356.jpg', ' A man in a black shirt crouches next to a dirty unfinished concrete edge while several shovels and other tools lean against a tree nearby .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('103631543.jpg', ' A Caucasian young woman in a white hooded sweatshirt sits at a table set for two in a lowly lit restaurant .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1039360778.jpg', ' A woman in a blue shirt and sunglasses lies on a red blanket in a grassy field with a bike set down next to her .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('103953336.jpg', ' Someone is standing on a long bridge with a cloudy blue sky in the background .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1039637574.jpg', ' A bride in a light pink dress poses for a picture with male relatives and is being photographed by a man in a cream shirt with white pants .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('10404007.jpg', ' Young white boy on a grassy area with a sad expression on his face .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1040426962.jpg', ' A man is cooking what appears to be green beans in a grill basket on a grill with a yellow lab standing by him while someone takes a picture from above .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('104136873.jpg', ' Three people are on a hilltop overlooking a green valley .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('104180524.jpg', ' A group of tourists is crossing a bridge that connects a walking path to a trail of nature .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1042020065.jpg', ' A young boy wearing a jersey looks down over a ledge at many boats in the water .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1042359076.jpg', ' A older man holds an object and is looking at two young girls that sit across from him at a table that is outside .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1042590306.jpg', ' A man is holding the hand of a woman up to his mouth in front of some buildings while another man looks on .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('104285082.jpg', ' A man with glasses is sitting a chair playing the oboe while a man in a purple shirt plays percussion and spectators look on .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1043819504.jpg', ' A group of 11 people in winter wear such as beanies , skiing jackets , gloves and backpacks are standing in snow paddles outside a house made of ice blocks while a person in front of the door seems to be leading them .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1043910339.jpg', ' A baseball player in red leaps into the air to avoid a player in blue , who is shortly behind him as he catches the ball , while other blue team members look on in the background .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1044434135.jpg', ' A man in the foreground wearing a white shirt and black pants riding a bicycle with a basket in a busy street .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1044764620.jpg', ' A man on a ladder is painting a brick wall in a warehouse .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1044798682.jpg', ' A man wearing a hat and a white shirt is cleaning windows .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1045124251.jpg', ' a blond-haired man with glasses and a blank tank top is sitting next to another man with glasses and headphones while sitting on a train .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1045309098.jpg', ' Juggling her shopping bags and Betty Boop backpack and young woman crosses a city street .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1045521051.jpg', ' A young man sits on the floor by the television with a fast food meal in front of him .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('10459869.jpg', ' Several asian people are eating together around a table .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('104669470.jpg', ' A woman with flowers in her hair balances a large bowl of assorted fruits on her head .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('104700891.jpg', ' A man wearing a gray jacket and blue work pants is standing in a hole in the ground','');
INSERT INTO image_metadata (title, description, uri) VALUES ('104763189.jpg', ' A shirtless young boy on a bicycle too big for him being supported by 3 other young shirtless boys in a grass field .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1047921035.jpg', ' A man in a bandanna and a dirty t-shirt , and a woman in a graphic t-shirt , are standing next to a oblong hole with smoke coming out .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('104816788.jpg', ' This little baby girl dressed whimsically in striped pantaloons is pictured so that one must ask which is bigger , her feet or her sleepy smile .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('104824673.jpg', ' An African individual is looking into the camera while dressed in varying beads and decorations that have a cultural relevance .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('104835889.jpg', ' A samurai warrior in full black dress takes his sword from the sheath on an outdoor training mat .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1048710776.jpg', ' a couple of several people sitting on a ledge overlooking the beach','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1049955899.jpg', ' A group of men and women are hiking through a dried up river bed littered with large rocks , which runs between two rocky walls in a dense green forest .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('105077209.jpg', ' A man with a badge is standing on a wood floor next to a structure .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1051205546.jpg', ' Two women in colorful dresses are sweeping water out of the street while a man watches .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1051290485.jpg', ' Two separate women , one wearing a white top and black pants , the other wearing all black and a pair of pink flip-flops , kneel on a gray brick sidewalk path in front of green and red bushes .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1051953669.jpg', ' A young girl wearing a multicolored holding an orange ball in her right hand walking through bright green grass behind a house','');
INSERT INTO image_metadata (title, description, uri) VALUES ('105223874.jpg', ' A young child wearing a blue shirt and sandals playing with a red toy while sitting on the floor .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1052358063.jpg', ' A little boy skateboarder is doing a trick on his board while another young skateboarder watches .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1053116826.jpg', ' Two little children , one boy and one girl , laugh as they sit on the grass .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1053243591.jpg', ' Young woman holding a bottle , reaching out from a bench to shake a man s hand .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('105335409.jpg', ' Man talking on a microphone and a crowd of people in front of him .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('105342180.jpg', ' A girl paddling down a large river , as seen from behind her .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1053804096.jpg', ' a girl with pigtails is playing in the ocean by the beach .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1054620089.jpg', ' A woman in jeans and a red coat and carrying a multicolored handbag spreads put her arms while leaping up from a cobblestone street .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('105493603.jpg', ' Two people sitting beside each other at a table with food on it smiling .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('105493628.jpg', ' White wine and appetizers on are displayed in an upscale restaurant .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1055623002.jpg', ' A group of four children wearing pajamas have a pillow fight .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1055753357.jpg', ' Two construction workers are sitting up on the side of a building .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1056198351.jpg', ' A smiling little boy holds a hand mixer in a bowl .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1056249424.jpg', ' Two boys , one with a yellow and orange ball , play in some water in front of a field .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1056338697.jpg', ' A woman with blond-hair wearing a blue tube top is waving on the side of the street .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1056359656.jpg', ' A young girl sits on a seat and looks at a train pamphlet .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1056415186.jpg', ' Two Asian girls laughing , as the girl on the right holds an instrument .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('105685221.jpg', ' Several people jogging outside on a sunny day in what seems to be a neighborhood , could be part of a marathon .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1056873310.jpg', ' Two dogs run towards each other on a rocky area with water in the background .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1057089366.jpg', ' A kid jumps off the diving board and into the swimming pool below .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1057210460.jpg', ' A guy stands by a window taking his overshirt off .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1057251835.jpg', ' A white dog is running down a rocky beach .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('105806535.jpg', ' A young man is bathing , with only his shorts on , in a large wooden pale .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1059514525.jpg', ' A person is sleeping on a bench on the sidewalk , across the street from a bus stop .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('10602072.jpg', ' Two young girls are playing in the forest ; the younger one is climbing a short tree and is about 2 feet off the ground .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('106027774.jpg', ' It looks as though a soldier is sleeping in a car on his way home after a deployment .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('106027978.jpg', ' Pink shirted woman sleeping in a car with blue and white blanket on her .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('106039369.jpg', ' One man wearing a white shirt is flipping a pancake by flinging it into the air .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1060605297.jpg', ' Firefighters converse with a man at the scene of an emergency .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1061467336.jpg', ' A few firefighters , wearing black , yellow , and pink jackets , standing next to a firetruck .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1061887159.jpg', ' A man is kneeling down with a child on a beach where bright blue and red boats are stationed in the background .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('106300392.jpg', ' A man in an orange hard hat and vest looks at an object in his hand while the man next to him stands on a ladder in order to reach the ceiling .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('106356264.jpg', ' A newsstand so packed with magazines , candy and coke-a-cola products that the smiling woman working behind the counter is easy to miss .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('10637120.jpg', ' A large earth moving machine creating a track with a man watching it closely with what looks like surveying equipment .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('106372282.jpg', ' A man sitting down with this head resting on his fists next to a man with his eyes closed and his together with dough sitting on a table in front of them both .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1063866640.jpg', ' Four men are sitting near a tree talking while another stands looking at a body of water and another is rowing a boat .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('106490881.jpg', ' A young boy in swimming trunks is walking with his arms outstretched on the beach .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('106514190.jpg', ' A skier is overlooking the beautiful white snow covered landscape .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1065323785.jpg', ' Kids riding on their bicycles near a mound of dirt with a hovel from a backhoe in front of the mound .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1065831604.jpg', ' A bunch of people in racing gear and helmets racing bicycles around a corner on wet pavement .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1066252238.jpg', ' A boy in a pink T-shirt is riding a bike over a sand pile while two others are riding in the street .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1066831905.jpg', ' Elderly man with cane bends down to look at some plants and is steadied from behind .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('106691539.jpg', ' A male surgeon wearing a red cap and teal scrubs performing surgery with two other men wearing teal scrubs .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1067180831.jpg', ' A black and white dog is attempting to catch a yellow and purple object in a low cut yard .','');
INSERT INTO image_metadata (title, description, uri) VALUES ('1067675215.jpg', ' A man lies on a mat in a parking lot between a brown SUV and a yellow pickup with an open door .','');
